Hw05 parallel execution
medvedevvu/otusgolang pull request #5
Opened 2021-10-18 18:49 UTC by medvedevvu

Почти получилось , но вылез datarace - ругается на строчку в тесте  - 28 строчка - atomic.AddInt32(&runTasksCount, 1). 
Бездомные горутины вроде нигде не остались. Не могу понять в чем проблема !

2021-10-23 13:20 UTC, agneum requested changes

2021-10-23 13:20 UTC, agneum commented on hw05_parallel_execution/run.go
> +			wg.Add(1)
Счётчик waitGroup необходимо увеличить до запуска горутины, иначе есть риск, что он просто не выполнится

2021-10-23 13:20 UTC, agneum commented on hw05_parallel_execution/run.go
> +	okChan := make(chan int, len(tasks))
Многовато каналов и все буферизированные, в том числе и из-за этого участок с select выглядит достаточно громоздко.
Предлагаю оставить один канал с задачами, а счётчик изменять и считывать атомарно либо с помощью мьютекса, либо с помощью atomic

2021-10-23 13:20 UTC, agneum commented on hw05_parallel_execution/go.mod
> +module github.com/medvedevvu/otusgolang/hw05_parallel_execution
Имя модуля выглядит корректно. Вероятно, проблема с кэшом

2021-10-31 17:24 UTC, medvedevvu commented
Внес изменения по рекомендации. Но хотел сделать по своему - через каналы - не получилось - не хватило знаний.

2021-11-01 03:19 UTC, agneum commented
> Внес изменения по рекомендации. Но хотел сделать по своему - через каналы - не получилось - не хватило знаний.

Спасибо за правки. Через канал тоже можно - ошибки будут отправляться в канал, из которого отдельная горутина-обработчик будет их подсчитывать и останавливать выполнение через вспомогательный сигнальный канал.

2021-11-01 03:19 UTC, agneum approved these changes

2021-11-07 13:51 UTC, merged