HW07 probe
medvedevvu/otusgolang pull request #7
Opened 2021-11-15 20:29 UTC by medvedevvu

2021-11-28 14:11 UTC, agneum requested changes
Спасибо за вариант решения. 
Есть предложения по улучшению программы, необходимо добавить показ прогресса копирования.
Итого: 6 баллов из 10

Просьба при создании PR использовать шаблон

2021-11-28 14:11 UTC, agneum commented on hw07_file_copying/copy.go
> +		fromFile.Close()
Если при открытии второго файла произойдёт ошибка, первый файл останется незакрытым

2021-11-28 14:11 UTC, agneum commented on hw07_file_copying/copy.go
> +	}
`limit` может быть очень большим. Не всегда будет доступно такое количество ресурсов.
Предлагаю выделить итерации и копировать мелкими порциями

2021-11-28 14:11 UTC, agneum commented on hw07_file_copying/copy.go
> +	}
Отсутствует вывод прогресса копирования в консоль
>Также необходимо выводить в консоль прогресс копирования в процентах (%), допускается использовать для этого стороннюю библиотеку.

2021-11-28 14:11 UTC, agneum commented on hw07_file_copying/copy_test.go
> +			toPath := tc.toPath
В тестах при работе с файлами, особенно при удалении, рекомендую использовать https://pkg.go.dev/os#CreateTemp

2021-11-28 14:11 UTC, agneum commented on hw07_file_copying/copy_test.go
> +			toInfo, _ := os.Stat(toPath)
Ошибки в тестах тоже важно проверять

2021-11-29 02:47 UTC, agneum approved these changes
Спасибо за добавление отображения прогресса копирования
Принято
Итого: 7 баллов из 10

2021-11-29 02:47 UTC, agneum commented on hw07_file_copying/copy.go
> +	barReader := bar.NewProxyReader(newReader)
`tempBuff` выглядит лишним звеном, можно сразу использовать `fromFile`

2021-11-29 19:01 UTC, medvedevvu commented
HW07 finished

2021-11-29 19:05 UTC, merged